# Generated by Django 4.2.7 on 2023-12-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_amount_alter_payments_date_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего обновления рассылки'),
        ),
    ]
